build-job:
  image: node:14-bullseye
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week

test-job1:
  image: node:14-bullseye
  stage: test
  script:
    - sed -i 's/pouchdb-browser/pouchdb-node/g' package.json
    - sed -i 's/pouchdb-browser/pouchdb-node/g' ./src/store/index.coffee
    - sed -i 's/pouchdb-browser/pouchdb-node/g' ./src/store/actions.coffee
    - yarn
    - yarn test:unit

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
