# frozen_string_literal: true

require Rails.root.join("app/lib/datawires/provider_registry")

Rails.application.config.to_prepare do
  Datawires::Providers.cards.register("document", "Boards::Cards::DocumentProvider")
  Datawires::Providers.cards.register("action", "Boards::Cards::ActionProvider")
  Datawires::Providers.cards.register("form", "Boards::Cards::FormProvider")
  Datawires::Providers.cards.register("query", "Boards::Cards::QueryProvider")
  Datawires::Providers.cards.register("metric", "Boards::Cards::MetricProvider")
  Datawires::Providers.cards.register("graph", "Boards::Cards::GraphProvider")
  Datawires::Providers.cards.register("image", "Boards::Cards::ImageProvider")
  Datawires::Providers.layouts.register("kanban", "Boards::Layouts::KanbanProvider")
  Datawires::Providers.layouts.register("grid", "Boards::Layouts::GridProvider")
  Datawires::Providers.layouts.register("list", "Boards::Layouts::ListProvider")
  Datawires::Providers.sections.register("document_collection", "Boards::Sections::Providers::DocumentCollectionProvider")
  Datawires::Providers.sections.register("meeting_collection", "Boards::Sections::Providers::MeetingCollectionProvider")
  Datawires::Providers.sections.register("proposal_collection", "Boards::Sections::Providers::ProposalCollectionProvider")
  Datawires::Providers.sections.register("membership_collection", "Boards::Sections::Providers::MembershipCollectionProvider")
  Datawires::Providers.sections.register("role_assignment_collection", "Boards::Sections::Providers::RoleAssignmentCollectionProvider")
  Datawires::Providers.sources.register("http_json", "Sources::Adapters::HttpJson")
  Datawires::Providers.sources.register("derived_metric", "Sources::Adapters::DerivedMetric")
  Datawires::Providers.renderers.register("line", "Presentations::SeriesRenderer")
  Datawires::Providers.renderers.register("sparkline", "Presentations::SeriesRenderer")
  Datawires::Providers.renderers.register("area", "Presentations::SeriesRenderer")
  Datawires::Providers.renderers.register("bar", "Presentations::SeriesRenderer")
  Datawires::Providers.aggregates.register("count", "Observations::AggregateProviders::Count")
  Datawires::Providers.aggregates.register("sum", "Observations::AggregateProviders::Sum")
  Datawires::Providers.aggregates.register("min", "Observations::AggregateProviders::Min")
  Datawires::Providers.aggregates.register("max", "Observations::AggregateProviders::Max")
  Datawires::Providers.aggregates.register("last", "Observations::AggregateProviders::Last")
  Datawires::Providers.aggregates.register("average", "Observations::AggregateProviders::Average")
  Datawires::Providers.derived_operations.register("add", "Metrics::DerivedOperations::Add")
  Datawires::Providers.derived_operations.register("subtract", "Metrics::DerivedOperations::Subtract")
  Datawires::Providers.derived_operations.register("multiply", "Metrics::DerivedOperations::Multiply")
  Datawires::Providers.derived_operations.register("divide", "Metrics::DerivedOperations::Divide")
end
